// Hardcoded sample data used to prove out rendering before any AI call is made,
// and as the initial map shown when the app first loads.

/** @type {import('./schema').MapData} */
export const sampleMapData = {
  title: 'Potato consumption per capita (sample data)',
  unit: 'kg/year',
  scale: 'sequential',
  data: [
    { iso3: 'BLR', value: 178 },
    { iso3: 'POL', value: 118 },
    { iso3: 'RUS', value: 112 },
    { iso3: 'UKR', value: 105 },
    { iso3: 'DEU', value: 68 },
    { iso3: 'GBR', value: 63 },
    { iso3: 'NLD', value: 79 },
    { iso3: 'IRL', value: 74 },
    { iso3: 'USA', value: 55 },
    { iso3: 'CAN', value: 58 },
    { iso3: 'FRA', value: 51 },
    { iso3: 'ESP', value: 31 },
    { iso3: 'ITA', value: 34 },
    { iso3: 'CHN', value: 41 },
    { iso3: 'IND', value: 22 },
    { iso3: 'BRA', value: 15 },
    { iso3: 'ARG', value: 44 },
    { iso3: 'AUS', value: 52 },
    { iso3: 'ZAF', value: 27 },
    { iso3: 'EGY', value: 24 },
    { iso3: 'NGA', value: 9 },
    { iso3: 'KEN', value: 12 },
    { iso3: 'JPN', value: 20 },
    { iso3: 'KOR', value: 18 },
    { iso3: 'IDN', value: 6 },
    { iso3: 'MEX', value: 16 },
    { iso3: 'TUR', value: 33 },
    { iso3: 'SWE', value: 60 },
    { iso3: 'NOR', value: 65 },
    { iso3: 'FIN', value: 61 },
  ],
}
